theme = "tokyonight_storm"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-c = ":clipboard-yank"
C-v = ":clipboard-paste-before"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

